services:
    app:
        build: .
        container_name: nodejs-app
        ports:
            - "3000:3000"
        environment:
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_NAME=${DB_NAME}
        depends_on:
            - mysql

    mysql:
        image: mysql:5.7
        container_name: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - mysql-data:/var/lib/mysql

volumes:
    mysql-data:
