services:
    app:
        build: .
        ports:
            - "${APP_PORT}:${APP_PORT}"
        env_file:
            - .env
        depends_on:
            - mysql
        restart: unless-stopped

    mysql:
        image: mysql:5.7
        ports:
            - "${MYSQL_TCP_PORT}:${MYSQL_TCP_PORT}"
        env_file:
            - .env
        volumes:
            - mysql-data:/var/lib/mysql

volumes:
    mysql-data:
